services:
  # MongoDB Database
  mongo:
    image: mongo:7
    container_name: guruconnect-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Backend API
  backend:
    build: ./BACKEND
    container_name: guruconnect-backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/mentorconnect
      - JWT_SECRET=supersecretkey
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
    depends_on:
      - mongo

  # Frontend React App
  frontend:
    build: ./Frontend
    container_name: guruconnect-frontend
    ports:
      - "5174:5174"
    environment:
      - VITE_API_TARGET=http://backend:5001
    depends_on:
      - backend


volumes:
  mongo-data:
